name: Build notebook image

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'The ref to build (tag/branch name/hash)'
        required: true
        type: string
        
      tag:
        description: 'The tag with which to tag the image'
        required: true
        type: string
      
      push_container_flag:
        description: 'Whatever to push the image'
        required: true
        type: boolean


env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # github.repository as <account>/<repo>
      - name: Build and push container image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/enterprise-gateway-compatible-notebook:${{ github.event.inputs.tag }}
          context: dockerfiles/notebook
          push: ${{ github.event.inputs.push_container_flag }}
